version: '3.3'
services:
    db:
        image: postgres:9.6
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        ports:
            - "5432"
        volumes:
            - docker-localshop-db-data:/var/lib/postgresql/data
        networks:
            - servicenet
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == worker
                preferences:
                    - spread: node.id
            resources:
                limits:
                    memory: 256M
                reservations:
                    memory: 256M
                    cpus: '0.1'
            restart_policy:
                delay: 5s
                window: 120s

    web:
        build: .
        image: ${DOCKER_IMAGE}
        environment:
            - DJANGO_SECRET_KEY
            - DATABASE_URL
            - DJANGO_MEDIA_ROOT
            - DJANGO_DEBUG
            - AUTH_LDAP_BIND_PASSWORD
            - AUTH_LDAP_SERVER_URI
            - AUTH_LDAP_BIND_DN
            - AUTH_LDAP_USER_SEARCH_BASE
            - AUTH_LDAP_USER_DN_TEMPLATE
        command: uwsgi --http 0.0.0.0:8000 --module localshop.wsgi --master --die-on-term
        ports:
            - "8000:8000"
        volumes:
            - /srv/data/docker-pypi-web-data:/media
        networks:
            - servicenet
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == worker
                preferences:
                    - spread: node.id
            resources:
                limits:
                    memory: 256M
                reservations:
                    memory: 256M
                    cpus: '0.1'
            restart_policy:
                delay: 5s
                window: 120s

    worker:
        image: ${DOCKER_IMAGE}
        environment:
            - DJANGO_SECRET_KEY
            - DATABASE_URL
            - DJANGO_MEDIA_ROOT
        entrypoint:
            localshop
        command: celery worker -B -E
        volumes:
            - /srv/data/docker-pypi-web-data:/media
        networks:
            - servicenet
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == worker
                preferences:
                    - spread: node.id
            resources:
                limits:
                    memory: 256M
                reservations:
                    memory: 256M
                    cpus: '0.1'
            restart_policy:
                delay: 5s
                window: 120s

    nonpriv_proxy:
      image: registry.osslabs.net/nonpriv-proxy:9c966a9-refresh-vault-token
      restart: always
      labels:
        com.openslate.service_ip: ${SERVICE_IP}/24
      networks:
        - hostnet
      environment:
        - SERVICE_IP
        - SERVICE_PORT
        - VAULT_ADDR
        - VAULT_CERTIFICATE_PATH=/v1/secret/ssl/star.osslabs.net
        - VAULT_TOKEN
      deploy:
        placement:
          constraints:
            - node.role == worker
        replicas: 1
        resources:
          limits:
            memory: 128M
          reservations:
            memory: 64M
        restart_policy:
          condition: any
          delay: 5s
          window: 120s



volumes:
    docker-localshop-db-data:
        external:
            name: docker-localshop-db-data


networks:
    hostnet:
      external:
        name: host

    servicenet:
        driver: overlay
        ipam:
            driver: default
            config:
                - subnet: ${DOCKER_SUBNET}
